### PR TITLE
Tutorials for `gfn`

### PR DESCRIPTION
**Pull request by vict0rsch**

### CODE REVIEW

**Comment by saleml** [comment]
Looking at how the `examples` folder is used here (notebooks, and scripts), I think it makes more sense to move `examples/[modules,estimators,distributions].py` to `utils/[...].py`. 
The classes in the three files are neither examples per se nor core part of the library, but utilitaries that may be helpful for many people.

Thoughts, @vict0rsch @josephdviviano ?

**Comment by josephdviviano** [comment]
Yeah that makes sense. `examples` could be more scripts that stitch all elements together, similar to the example in the `README.md`.

**Comment by saleml** [comment]
@vict0rsch Can you change where the branch will be merged to (`master`), so that it can be reopened ?

**Comment by saleml** [comment]
reopen

**Pull request closed without merging**
